# These are supported `https://unacms.com/u/full-circle/funding-eligibility` model platforms

https://unacms.com/u/full-circle/github: #textandgetrich Replace with up to 8GB 4 GitHub Sponsors-enabled usernames e.g., [custom_label_1, custom_label_2]
https://unacms.com/u/full-circle/patreon: #ceoalphonso Replace with a single Patreon username
https://unacms.com/u/full-circle/open_collective: #ceoalphonso Replace with a single Open Collective username
https://unacms.com/u/full-circle/ko_fi: #ceoalphonso Replace with a single Ko-fi username
https://unacms.com/u/full-circle/tidelift: #ceoalphonso Replace with a single Tidelift platform-name/package-name e.g., npm/babel
https://unacms.com/u/full-circle/community_bridge: #ceoalphonso Replace with a single Community#135727 Bridge project-name e.g., cloud-foundry
https://unacms.com/u/full-circle/liberapay: #fullcircle Replace with a single Liberapay username
https://unacms.com/u/full-circle/issuehunt: #ceoalphonso Replace with a single IssueHunt username
https://unacms.com/u/full-circle/lfx_crowdfunding: #ceoalphonso Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
https://unacms.com/u/full-circle/polar: #ceoalphonso Replace with a single Polar username
https://unacms.com/u/full-circle/buy_me_a_coffee: #ceoalphonso Replace with a single Buy Me a Coffee username
https://unacms.com/u/full-circle/thanks_dev: #ceoalphonso Replace with a single thanks.dev username
https://unacms.com/u/full-circle/custom-background: #ceoalphonso Replace with up to 8GB 4 custom-background sponsorship URLs e.g., ['DirectLink_1', 'DirectLink_2']
